In [3]:
import numpy as np
from edtrace import text, link, image, note
import torch
from einops import einsum, reduce, rearrange
import timeit


In [7]:
x = np.array(42)
print(x)

42


In [8]:
s = x.shape
print(s)

()


In [9]:
x = np.array([1, 2, 3])
print(x)

[1 2 3]


In [10]:
s = x.shape
print(s)

(3,)


In [11]:
x = np.array([
    [1, 2, 3],
    [4, 5, 6],
])
print(x)

[[1 2 3]
 [4 5 6]]


In [12]:
s = x.shape
print(s)

(2, 3)


In [13]:
x = np.array([
    [
        [1, 2, 3],
        [4, 5, 6],
    ],
    [
        [7, 8, 9],
        [10, 11, 12],
    ],
])
print(x)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [14]:
s = x.shape
print(s)

(2, 2, 3)


In [15]:
y = x[1]
print(y)

[[ 7  8  9]
 [10 11 12]]


In [16]:
y = x[0]
print(y)

[[1 2 3]
 [4 5 6]]


In [17]:
y = x[1][0]
print(y)

[7 8 9]


In [18]:
y = x[1, 0, 2]
print(y)

9


In [ ]:
y = x[1][0][2] #batch, row, column in order
print(y)

9


In [20]:
x = np.zeros((2, 3))
print(x)

[[0. 0. 0.]
 [0. 0. 0.]]


In [21]:
x = np.ones((2, 3))
print(x)

[[1. 1. 1.]
 [1. 1. 1.]]


In [22]:
x = np.random.randn(2,3)
print(x)

[[-0.3295137   0.52349648 -0.72242796]
 [ 1.02319593 -0.71654365  2.11067465]]


In [23]:
x = np.eye(3)
print(x)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [24]:
x = np.diag([1,2,3])
print(x)

[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [26]:
D = 2
x = np.ones(D)
print(x)

[1. 1.]


In [27]:
N = 3
x = np.ones((N, D))
print(x)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [28]:
L = 4
x = np.ones((N, L, D))
print(x)

[[[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]]


In [29]:
H = 2
W = 2
C = 3
x = np.ones((N, H, W, C))
print(x)

[[[[1. 1. 1.]
   [1. 1. 1.]]

  [[1. 1. 1.]
   [1. 1. 1.]]]


 [[[1. 1. 1.]
   [1. 1. 1.]]

  [[1. 1. 1.]
   [1. 1. 1.]]]


 [[[1. 1. 1.]
   [1. 1. 1.]]

  [[1. 1. 1.]
   [1. 1. 1.]]]]


In [30]:
Din = 3
Dout = 2
W = np.ones((Din, Dout))
print(W)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [31]:
x = np.random.randn(2,3)
print(x)

[[-2.23058838 -1.94793395 -0.51778431]
 [-1.21784935  0.34268456 -0.19845311]]


In [32]:
y = x[0]
print(y)

[-2.23058838 -1.94793395 -0.51778431]


In [33]:
y = x[:,1]
print(y)

[-1.94793395  0.34268456]


In [36]:
y = x.transpose(1,0)
print(y)

[[-2.23058838 -1.21784935]
 [-1.94793395  0.34268456]
 [-0.51778431 -0.19845311]]


In [37]:
x[0][0] = 100
print(x)

[[100.          -1.94793395  -0.51778431]
 [ -1.21784935   0.34268456  -0.19845311]]


In [38]:
x = np.array([1,4,9])
print(x)

[1 4 9]


In [39]:
y = np.power(x, 2)
print(y)

[ 1 16 81]


In [40]:
y = np.sqrt(x)
print(y)

[1. 2. 3.]


In [41]:
y = x + x
print(y)

[ 2  8 18]


In [42]:
y = x * 3
print(y)

[ 3 12 27]


In [43]:
y = x / 2
print(y)

[0.5 2.  4.5]


In [44]:
x = np.ones((3,3))
print(x)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [45]:
y = np.triu(x)
print(y)

[[1. 1. 1.]
 [0. 1. 1.]
 [0. 0. 1.]]


In [46]:
y = np.tril(x)
print(y)

[[1. 0. 0.]
 [1. 1. 0.]
 [1. 1. 1.]]


In [47]:
y = np.zeros_like(x)
print(y)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [48]:
y = np.ones_like(x)
print(y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [54]:
x = np.ones((4,6))
print(x)

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


In [53]:
w = np.ones((6,3))
print(w)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [56]:
y = x @ w
print(y)

[[6. 6. 6.]
 [6. 6. 6.]
 [6. 6. 6.]
 [6. 6. 6.]]


In [57]:
N = 16
x = np.ones((N, N))
w = np.ones((N, N))


In [58]:
def slow_matmul() -> np.ndarray:
    y = np.zeros((N, N))
    for i in range(N):
        for j in range(N):
            for k in range(N):
                y[i, j] += x[i, k] * w[k, j]
    return y

In [59]:
python_time = timeit.timeit(slow_matmul, number=1)
print(f"Python matmul took {python_time:.4f} seconds")

Python matmul took 0.0019 seconds


In [60]:
numpy_time = timeit.timeit(lambda: x @ w, number=1)
print(f"Numpy matmul took {numpy_time:.4f} seconds")

Numpy matmul took 0.0026 seconds


In [62]:
speedup = python_time / numpy_time
print(speedup)

0.7354705589969777


In [63]:
x = torch.ones(2,2,3)
print(x)

tensor([[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]])


In [64]:
y = torch.ones(2,2,3)
print(y)

tensor([[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]])


In [65]:
z = x @ y.transpose(-2,-1)
print(z)

tensor([[[3., 3.],
         [3., 3.]],

        [[3., 3.],
         [3., 3.]]])


In [66]:
x = torch.ones(3,4)
print(x)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [67]:
y = torch.ones(4,3)
print(y)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [68]:
z = x @ y
print(z)

tensor([[4., 4., 4.],
        [4., 4., 4.],
        [4., 4., 4.]])


In [69]:
z = einsum(x, y, 'seq1 hidden, hidden seq2 -> seq1 seq2')
print(z)

tensor([[4., 4., 4.],
        [4., 4., 4.],
        [4., 4., 4.]])


In [70]:
x = torch.ones(2,3,4)
print(x)

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])


In [71]:
y = torch.ones(2,3,4)
print(y)

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])


In [72]:
z = x @ y.transpose(-2,-1)
print(z)

tensor([[[4., 4., 4.],
         [4., 4., 4.],
         [4., 4., 4.]],

        [[4., 4., 4.],
         [4., 4., 4.],
         [4., 4., 4.]]])


In [73]:
z = einsum(x,y, 'batch seq1 hidden, batch seq2 hidden -> batch seq1 seq2')
print(z)

tensor([[[4., 4., 4.],
         [4., 4., 4.],
         [4., 4., 4.]],

        [[4., 4., 4.],
         [4., 4., 4.],
         [4., 4., 4.]]])


In [74]:
x = torch.ones(2,3,4)
print(x)

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])


In [75]:
y = x.sum(dim=-1)
print(y)

tensor([[4., 4., 4.],
        [4., 4., 4.]])


In [76]:
y = reduce(x, '... hidden -> ...', 'sum')
print(y)

tensor([[4., 4., 4.],
        [4., 4., 4.]])


In [77]:
x = torch.ones(3,8)
print(x)

tensor([[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]])


In [78]:
w = torch.ones(4,4)
print(w)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [79]:
x = rearrange(x, '... (heads hidden1) -> ... heads hidden1', heads=2)
print(x)

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.]]])


In [80]:
x = einsum(x,w,'... hidden1, hidden1 hidden2 -> ... hidden2')
print(x)

tensor([[[4., 4., 4., 4.],
         [4., 4., 4., 4.]],

        [[4., 4., 4., 4.],
         [4., 4., 4., 4.]],

        [[4., 4., 4., 4.],
         [4., 4., 4., 4.]]])


In [81]:
x = rearrange( x, '... heads hidden2 -> ... (heads hidden2)')
print(x)

tensor([[4., 4., 4., 4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4., 4., 4., 4.]])
