In [66]:
from edtrace import text, link, plot, note, image, Input
from dataclasses import dataclass
import numpy as np
from altair import Chart, Data
from einops import einsum
from graphviz import Digraph



ImportError: cannot import name 'Input' from 'edtrace' (/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/edtrace/__init__.py)

In [2]:
x = np.array([0, 1, 10])
print(x)

[ 0  1 10]


In [3]:
y = einsum(x, 'i -> i')
print(y)

[ 0  1 10]


In [4]:
y = einsum(x, 'i ->')
print(y)

11


In [5]:
y = einsum(x, x, 'i, i -> i')
print(y)

[  0   1 100]


In [6]:
y = einsum(x, x, 'i, i ->')
print(y)

101


In [8]:
y = einsum(x, x, 'i, j -> i j')
print(y)

[[  0   0   0]
 [  0   1  10]
 [  0  10 100]]


In [9]:
y = einsum(x, x, x, 'i, i, i -> i')
print(y)

[   0    1 1000]


In [10]:
y = einsum(x, x, x, 'i, j, k -> i j k')
print(y)

[[[   0    0    0]
  [   0    0    0]
  [   0    0    0]]

 [[   0    0    0]
  [   0    1   10]
  [   0   10  100]]

 [[   0    0    0]
  [   0   10  100]
  [   0  100 1000]]]


In [11]:
m = np.array([
    [0, 1, 2],
    [1, 10, 0]
])
print(m)

[[ 0  1  2]
 [ 1 10  0]]


In [13]:
y = einsum(m , 'i j -> ')
print(y)

14


In [14]:
y = einsum(m, 'i j -> i')
print(y)

[ 3 11]


In [15]:
y = einsum(m, 'i j -> j')
print(y)

[ 1 11  2]


In [16]:
y = einsum(m, 'i j -> j i')
print(y)

[[ 0  1]
 [ 1 10]
 [ 2  0]]


In [17]:
y = einsum(m, x, 'i j, j -> i')
print(y)

[21 10]


In [24]:
y = einsum(m, m, 'i k, j k -> i j')
print(y)

[[  5  10]
 [ 10 101]]


In [26]:
y = einsum(m, m, 'k i, k j -> i j')
print(y)

[[  1  10   0]
 [ 10 101   2]
 [  0   2   4]]


In [27]:
x = np.array([[1,2,0], [0,-1,1]])
print(x)

[[ 1  2  0]
 [ 0 -1  1]]


In [28]:
y = np.array([0,3])
print(y)

[0 3]


In [29]:
w = np.array([1, 0, 1])
print(w)

[1 0 1]


In [30]:
predictions = x @ w
print(predictions)

[1 1]


In [31]:

residuals = predictions - y
print(residuals)

[ 1 -2]


In [32]:
losses = residuals ** 2
print(losses)

[1 4]


In [33]:
total_loss = np.sum(losses)
print(total_loss)

5


In [34]:
def objective(w: np.ndarray) -> float:
    loss = (x @ w - y) ** 2
    return loss



In [35]:
loss = objective(np.array([1, 0, -1]))
print(loss)

[ 1 16]


In [36]:
def f(x: float) -> float:
    return x ** 2

In [38]:
values = [{"x": x, "y": f(x)} for x in np.linspace(-2, 2, 30)]

In [49]:
import altair as alt
alt.renderers.enable('html')
Chart(Data(values = values)).mark_line().encode(x = 'x:Q', y = 'y:Q')



alt.Chart(...)

In [50]:
dx = 1e-4
x = 1
y = f(x)
print(y)

1


In [51]:
new_y = f(x + dx)
print(new_y)

1.00020001


In [52]:
dy = (new_y - y) / dx
print(dy)

2.000099999999172


In [53]:
def df(x: float) -> float:
    return 2 * x


In [54]:
dy = df(x)
print(dy)

2


In [55]:
def f(x1: float, x2: float) -> float:
    return x1 ** 2 + x2 ** 2

In [56]:
y = f(1, 2)
print(y)

5


In [57]:
def df_dx1(x1: float, x2: float) -> float:
    return 2 * x1

def df_dx2(x1: float, x2: float) -> float:
    return 2 * x2

In [58]:
dy_x1 = df_dx1(1, 2)
print(dy_x1)

2


In [59]:
dy_x2 = df_dx2(1, 2)
print(dy_x2)

4


In [60]:
def f(x: np.ndarray):
    return np.sum(x ** 2)

In [61]:
y = f(np.array([1, 2]))
print(y)

5


In [62]:
def f(x1: float, x2: float) -> float:
    return x1 ** 2 + x2 ** 2


In [67]:
!git clone https://github.com/stanford-cs221/autumn2025-lectures.git


Cloning into 'autumn2025-lectures'...
remote: Enumerating objects: 589, done.
remote: Counting objects: 100% (67/67), done.
remote: Compressing objects: 100% (57/57), done.
remote: Total 589 (delta 23), reused 48 (delta 10), pack-reused 522 (from 1)
Receiving objects: 100% (589/589), 52.35 MiB | 7.22 MiB/s, done.
Resolving deltas: 100% (271/271), done.


In [97]:
import sys
sys.path.append('autumn2025-lectures')
from backpropagation import Input, Add, Squared, backpropagation, Multiply, Subtract



In [71]:
x1 = Input("x1", np.array(2.0))
print(x1)

In [72]:
x2 = Input("x2", np.array(3.0))
print(x2)

In [75]:
sum = Add("sum", x1, x2)
print(sum)

In [77]:
sum.forward()
print(sum)

In [79]:
y = Squared("y", sum)
print(y)

In [80]:
y.forward()

In [81]:
y.grad = np.ones_like(y.value)
print(y.grad)

1.0


In [82]:
sum.grad = np.zeros_like(sum.value)
print(sum.grad)

0.0


In [83]:
x1.grad = np.zeros_like(x1.value)
print(x1.grad)

0.0


In [84]:
x2.grad = np.zeros_like(x2.value)
print(x2.grad)

0.0


In [85]:
y.backward()

In [86]:
sum.backward()

In [87]:
x1 = Input("x1", np.array(2.0))
x2 = Input("x2", np.array(3.0))
sum = Add("sum", x1, x2)

In [88]:
y = Squared("y", sum)

In [91]:
backpropagation(y)

In [92]:
x = Input("x", np.array([[1., 2, 0], [0, -1, 1]]))
y = Input("y", np.array([[0.], [3]]))
w = Input("w", np.array([[1.], [0], [1]]))

In [95]:
predictions = Multiply("predictions", x, w)
print(predictions)

In [98]:
residuals = Subtract("residuals", predictions, y)

In [99]:
losses = Squared("losses", residuals)

In [100]:
ones = Input("ones", np.ones((1, 2)))

In [101]:
total_loss = Multiply("total_loss", ones, losses)

In [ ]:
backpropagation(total_loss)
